---
title: "Tuition Variation Research"
author: "Rory Quinlan"
date: "2024-01-25"
output: html_document
---

<center> <h1> **Set up** </h1> </center>

```{r, warning=FALSE, message=F}

library(readxl)
library(dplyr)
library(viridis)
require(caret)
require(MASS)

# Most complete data use as a base
Base<- read_excel("C:\\Users\\roryq\\Downloads\\Stat 1223\\CollegeDatEdited.xlsx")
BaseData<- as.data.frame(Base)


# Second data to be joined
Rank<-  read_excel("C:\\Users\\roryq\\Downloads\\Stat 1223\\collegeRank.xlsx")
RankData<- as.data.frame(Rank)

# Change column name to match other data set
colnames(RankData)[which(names(RankData) == "College Name")] <- "University"

# Third data to be joined
CityData<- read_excel("C:\\Users\\roryq\\Downloads\\Stat 1223\\schoolInfo.xlsx")

# Crime data to merge
CrimeData<- read_excel("C:\\Users\\roryq\\Downloads\\Stat 1223\\Crime.xlsx")
```

<center> <h1> **Merge 1 and 2** </h1> </center>

```{r, message=F,warning=F}

# Merge 1 with Rank and Base


M1 <- merge(x=BaseData,y=RankData, 
      by.x=c("University","University"), 
      by.y=c("University","University"))


# Create new column in data frame that calculates that acceptance rate for the school, and a column that calculates total number of undergrads
M1$number_Undergrads<- M1$F.Undergrad+ M1$P.Undergrad
M1$Acceptance_rate<- (M1$Accept/M1$Apps)*100

```

```{r}

# Merge 2 with City and M1
M2<- left_join(x= M1, y= CityData, by = "University")

```

```{r}

# Export csv for Assignment checking submission and read that cvs back (requirement for assignment)

    # write.csv(M2, "C:\\Users\\roryq\\Downloads\\M2.csv",           row.names=FALSE)

M2.0<- read_excel("C:\\Users\\roryq\\Downloads\\Stat 1223\\M2.xlsx")

```




```{r}

# Remove excess/duplicate columns (by names)
M2.1 <- subset(M2.0, select = -c(P.Undergrad,F.Undergrad,Enroll,Top10perc,Top25perc,Personal,Apps,Accept,ranking,Terminal,PhD,primaryKey,Private,businessRepScore,engineeringRepScore,enrollment, state,Books))


# Or remove columns (by index)
M2.2 <- M2.1[-c(22,19,6,21,20)]

```




\pagebreak

<center> <h1> **Merge 3** </h1> </center>


```{r, message=F, warning=F}

# Merge 3;  Crime and M2.2



# Change column name to match M3 for join
colnames(CrimeData)[which(names(CrimeData) == "NMCNTY")] <- "city"
colnames(CrimeData)[which(names(CrimeData) == "Overall Rank")] <- "City Rank"



# Merge 3
M3<- inner_join(x= M2.2, y= CrimeData, by = "city")


# Remove excess/duplicate columns (by name)
M3.1 <- subset(M3, select = -c(NtnlPrkCnt,FIPS,LSTATE))


#  Or remove columns (by index)
M3.2 <- M3.1[-c(35,37:45,19,31,20,18,27,30,22,25,28,29,26,47)]


```

```{r}

# Export csv for Assignment checking submission and read that cvs back (requirement for assignment)

  #write.csv(M3.2, "C:\\Users\\roryq\\Downloads\\M3.2.csv",        row.names=FALSE)

obs_60_final<- read_excel("C:\\Users\\roryq\\Downloads\\Stat 1223\\M3.2.xlsx")

# Change column names
colnames(obs_60_final)[which(names(obs_60_final) == "2016 Crime Rate")] <- "Crime_Rate"
colnames(obs_60_final)[which(names(obs_60_final) == "2022 Median Income")] <- "Median_Income"
colnames(obs_60_final)[which(names(obs_60_final) == "Cost of Living")] <- "Cost_of_Living"

```

```{r}

# convert crime rate to be adjusted by 1000
vec<- c(18,24,16,19,21,19,13,48,36,31,42,21,27,15,16,42,52,37,8,44,33,33,50,3,34,13,18,21,50,24,10,21,45,29/22,26,15,11,42,24,15,36,31,15,8, 0, 42,22, 68,32,51,16,32,51,35,13,51,19,27, NA,NA)

vec2<-numeric()
for(i in vec){
  vec2<- c(vec2,i/1000)
}

obs_60_final$Crime.Rate<-vec2
```

```{r}
# Display number of observations and column names for final dataset to model
colnames(obs_60_final)
nrow(obs_60_final)
```





<center> <h1> **Descriptive Statistics** </h1> </center>

```{r}

# Create Descriptive Stats


# Filter by private or public schools
Private_60 = obs_60_final[which(obs_60_final$institutionalControl == "private"),]
Public_60 = obs_60_final[which(obs_60_final$institutionalControl == "public"),]


labels<- c("Mean Cost Private",
"Mean Cost Public",
"Mean Expend Public",
"Mean Expend Private",
"sd Cost Public",
"sd Cost Public",
"sd Cost Private",
"sd Expend Private",
"sd Expend Public",
"sd income Public",
"Mean income Public",
"sd income Private",
"Mean income Private")

values<-c(mean(Private_60$Tuition)
,mean(Public_60$Tuition)
,mean(Public_60$Expend)
,mean(Private_60$Expend)
,sd(Public_60$Tuition)
,sd(Public_60$Tuition)
,sd(Private_60$Tuition)
,sd(Private_60$Expend)
,sd(Public_60$Expend)
,sd(Public_60$Median_Income)
,mean(Public_60$Median_Income)
,sd(Private_60$Median_Income)
,mean(Private_60$Median_Income))


# View descriptive stats as a data frame
as.data.frame(cbind(labels,values))


```

```{r}

# Create Descriptive Stats

values2<-
c(sd(as.numeric(Public_60$number_Undergrads))
,mean(as.numeric(Public_60$number_Undergrads))
,sd(as.numeric(Private_60$number_Undergrads))
,mean(as.numeric(Private_60$number_Undergrads)))


labels2<-
c("sd undergrad Public",
"Mean undergrad Public",
"sd undergrad Private",
"Mean undergrad Private")

# View descriptive stats as a data frame
as.data.frame(cbind(labels,values))
```


```{r}

# Number of observations of private schools
nrow(Private_60)

# Number of observations of public schools
nrow(Public_60)

```

```{r}

hist(Private_60$Rank, xlab= "School Rank", main= "Histogram of Private school Ranks", col= viridis(8))
hist(Public_60$Rank, xlab= "School Rank", main= "Histogram of Public School Ranks" , col= viridis(7) )
```


<center> <h1> **Model (Data Set Complete, 60 Observations)** </h1> </center>

```{r}
# Create linear regression model with all factors we are interested
 model = lm(Tuition ~ Rank+S.F.Ratio+Unemployment+Diversity_Rank_Race+ Expend+perc.alumni +institutionalControl+number_Undergrads+Median_Income+Grad.Rate+ Crime.Rate+Cost_of_Living+AVG_C_two_I , data = obs_60_final)
 
# Print model summary
summary(model)
```

```{r}

# View residuals to check heteroskewdasticity
res=resid(model)
plot(fitted(model), res, pch=19)
abline(0,0)
```


```{r}
# Check for interaction terms



# Create 2 linear regression models one with private and one with public to compare expenditure per student and tuition levels
model_pri60E = lm(Tuition ~ Expend, data = Private_60)
model_pub60E = lm(Tuition ~ Expend, data = Public_60)

# Scatterplot with groups
# Specify colors to be used in scatterplot

colors = c("red", "blue")  
plot(obs_60_final$Expend, obs_60_final$Tuition, pch = 19, col = colors[factor(obs_60_final$institutionalControl)], xlab = "Expend", ylab = "Tuition")

abline(model_pri60E, col = "red")  # Plot the regression line for private colleges

abline(model_pub60E, col = "blue")   # Plot the regression line for public colleges
```


```{r, warning=F, message=F}

# Create 2 linear regression models one with private and one with public to compare expenditure per student and tuition levels
model_pri60 = lm(Tuition ~ Rank, data = Private_60)
model_pub60 = lm(Tuition ~ Rank, data = Public_60)

# Scatterplot with groups
colors = c("red", "blue")  # Specify colors to be used in scatterplot
plot(obs_60_final$Rank, obs_60_final$Tuition, pch = 19, col = colors[factor(obs_60_final$institutionalControl)], xlab = "Rank", ylab = "Tuition")
abline(model_pri60, col = "red")  # Plot the regression line for private colleges
abline(model_pub60, col = "blue")   # Plot the regression line for public colleges
```


```{r}

# Model selection
# Use Forward and Backward Stepwise Regression Selection

min_model = lm(Tuition ~ 1, data = obs_60_final)
max_model = formula(lm(Tuition ~ Rank + S.F.Ratio + Unemployment + Diversity_Rank_Race + Expend+ institutionalControl+number_Undergrads+Median_Income+Grad.Rate+Crime.Rate+Cost_of_Living, data = obs_60_final))
best_model = step(min_model, direction = "both", scope = max_model)

# View best model
best_model
```

```{r}

# Model validation
# Use Leave One Our Cross Validation

ctrl = trainControl(method = "LOOCV")
model1 = train(Tuition ~ Rank + institutionalControl + Median_Income + 
Diversity_Rank_Race + Unemployment + number_Undergrads + Expend, data = obs_60_final, method = "lm", trControl = ctrl)
model1$results


```

```{r}
# print summary of best model
summary(best_model)
```

```{r}
# Plot residuals and check heteroskewdasticity
res=resid(best_model)
plot(fitted(best_model), res, pch=19, main="Residual plot", ylab="Residual", xlab="Model")
abline(0,0)
```

```{r}
summary(lm(Tuition ~ Rank, data = obs_60_final))
```



